version: '3'

services:
  DFK.conta:
    image: DFK.conta
    build:
      context: .
      dockerfile: DFK.Conta\Dockerfile

  DFK.service.conta:
    image: DFK.service.conta
    build:
      context: .
      dockerfile: DFK.Service.Conta\Dockerfile

