version: '3'

services:
  hubfintech.conta:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  hubfintech.service.conta:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

