USE [master]
GO
/****** Object:  Database [teste]    Script Date: 19/04/2018 20:28:38 ******/
CREATE DATABASE [teste]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'teste', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\teste.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'teste_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\teste_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [teste] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [teste].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [teste] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [teste] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [teste] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [teste] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [teste] SET ARITHABORT OFF 
GO
ALTER DATABASE [teste] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [teste] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [teste] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [teste] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [teste] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [teste] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [teste] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [teste] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [teste] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [teste] SET  DISABLE_BROKER 
GO
ALTER DATABASE [teste] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [teste] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [teste] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [teste] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [teste] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [teste] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [teste] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [teste] SET RECOVERY FULL 
GO
ALTER DATABASE [teste] SET  MULTI_USER 
GO
ALTER DATABASE [teste] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [teste] SET DB_CHAINING OFF 
GO
ALTER DATABASE [teste] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [teste] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [teste] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'teste', N'ON'
GO
USE [teste]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 19/04/2018 20:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Cliente](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[DataNascimento] [datetime] NULL,
	[DataCadastro] [datetime] NOT NULL,
	[CPF] [varchar](11) NULL,
	[NomeCompleto] [varchar](60) NULL,
	[CNPJ] [varchar](14) NULL,
	[RazaoSocial] [varchar](60) NULL,
	[NomeFantasia] [varchar](60) NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Conta]    Script Date: 19/04/2018 20:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Conta](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ContaPaiId] [bigint] NULL,
	[Matriz] [bit] NOT NULL,
	[Nome] [varchar](60) NOT NULL,
	[ClienteId] [bigint] NOT NULL,
	[Status] [smallint] NOT NULL,
	[DataCriacao] [datetime] NOT NULL,
 CONSTRAINT [PK_Conta] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Transacao]    Script Date: 19/04/2018 20:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Transacao](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[CodigoTransacao] [varchar](50) NOT NULL,
	[ReferenciaId] [bigint] NULL,
	[ContaOrigemId] [bigint] NULL,
	[ContaDestinoId] [bigint] NOT NULL,
	[DataCadastro] [datetime] NOT NULL,
	[DataAtualizacao] [datetime] NOT NULL,
	[Valor] [decimal](9, 2) NULL,
 CONSTRAINT [PK_Transacao] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_Cliente_CPF]    Script Date: 19/04/2018 20:28:40 ******/
CREATE NONCLUSTERED INDEX [IX_Cliente_CPF] ON [dbo].[Cliente]
(
	[CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_Cliente_CPNJ]    Script Date: 19/04/2018 20:28:40 ******/
CREATE NONCLUSTERED INDEX [IX_Cliente_CPNJ] ON [dbo].[Cliente]
(
	[CNPJ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Conta]  WITH CHECK ADD  CONSTRAINT [FK_Conta_Cliente] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([Id])
GO
ALTER TABLE [dbo].[Conta] CHECK CONSTRAINT [FK_Conta_Cliente]
GO
ALTER TABLE [dbo].[Transacao]  WITH CHECK ADD  CONSTRAINT [FK_Transacao_ContaDestino] FOREIGN KEY([ContaDestinoId])
REFERENCES [dbo].[Conta] ([Id])
GO
ALTER TABLE [dbo].[Transacao] CHECK CONSTRAINT [FK_Transacao_ContaDestino]
GO
ALTER TABLE [dbo].[Transacao]  WITH CHECK ADD  CONSTRAINT [FK_Transacao_ContaOrigem] FOREIGN KEY([ContaOrigemId])
REFERENCES [dbo].[Conta] ([Id])
GO
ALTER TABLE [dbo].[Transacao] CHECK CONSTRAINT [FK_Transacao_ContaOrigem]
GO
USE [master]
GO
ALTER DATABASE [teste] SET  READ_WRITE 
GO

